apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Test
on:
  workflow_dispatch:

  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "**"

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://byrnedo/alpine-curl
        shell: sh
        run: |
          echo "hello test"
          echo "${{ cloudbees.api.token }}" | base64
          curl --location 'https://api.saas-preprod.beescloud.com/reserved/v1/components/769dd697-e077-4f5e-b4cc-701b090656ac/statuses' \
          --data "{\"orgId\":\"5c2a62c4-edb2-472e-79cf-58e08dd6a8be\", \
           \"componentId\": \"0a2b7529-ee4b-4c8a-94ca-310cab65e886\", \
           \"status_code\": \"SCM_TRIGGER_ERROR\"}" \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer ${{ cloudbees.api.token }}"

      - name: Test workflow allowed
        uses: docker://byrnedo/alpine-curl
        shell: sh
        run: |
          echo "hello wf allowed"
          echo "${{ cloudbees.api.token }}" | base64
          curl --location 'https://api.saas-preprod.beescloud.com/v1/resources/92dcd653-8d70-42ee-a33b-521008f9ad19/commits/26374c8ca8a146e2255b2edc209f9fcaff2806a3/tests/123' \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer ${{ cloudbees.api.token }}"
