apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Sc Test Wkflow 2
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testing create workflow and merge from branch"
